= Google Play Overview

With buddybuild, you can deploy builds directly to Google Play! All you
need to do is create a Private Key from the Google Play Developer
Console (.JSON file) and upload that to buddybuild. From there, you can
select which variant to upload, which track to upload to, and which
buddybuild SDK features you'd like to include in the build you're
uploading.

[CAUTION]
=========
**Before you can deploy builds to Google Play**

. First link:../keystores/manage.adoc[upload the APK Keystore]
  associated with the variant you would like to deploy.

. The APK must be uploaded manually, at least once, through the Google
  Play Developer Console, which sets up the application inside the
  Google Play Developer Console allowing Buddybuild to automatically
  deploy on your behalf from then on.
=========

== Follow the steps below to connect and deploy to Google Play:

. link:developer_console.adoc[Create a private key and setup permissions
  from the Google Play Developer Console]

. link:automatic.adoc[Deploying automatically to Google Play]

. link:manual.adoc[Deploying manually to Google Play]
