---
titletext: Supported tools and platforms for Android and Docker
description: >
  Android / Docker environment tools and platform versions supported by buddybuild.
---
= Tools and Platform versions for Android / Docker environment

== Base Image

Debian GNU/Linux 8 (jessie)

== Android SDK

[cols="a,a"]
|===
| build tools
| 17.0.0
18.0.1
18.1.0
18.1.1
19.0.0
19.0.1
19.0.2
19.0.3
19.1.0
20.0.0
21.0.0
21.0.1
21.0.2
21.1.0
21.1.1
21.1.2
22.0.0
22.0.1
23.0.0
23.0.1
23.0.2
23.0.3
24.0.0
24.0.1

| platforms
| android-10
android-11
android-12
android-13
android-14
android-15
android-16
android-17
android-18
android-19
android-20
android-21
android-22
android-23
android-24

| system-images
| android-22/default/armeabi-v7a
android-22/default/x86_64
android-22/google_apis/armeabi-v7a
android-22/google_apis/x86_64
android-23/default/armeabi-v7a
android-23/default/x86_64
android-23/google_apis/armeabi-v7a
android-23/google_apis/x86_64

| extras/m2repository
| com/android/support/constraint/constraint-layout/1.0.0-alpha8
com/android/support/constraint/constraint-layout/1.0.0-alpha7
com/android/support/constraint/constraint-layout/1.0.0-alpha6
com/android/support/constraint/constraint-layout/1.0.0-alpha5
com/android/support/constraint/constraint-layout/1.0.0-alpha4
com/android/support/constraint/constraint-layout/1.0.0-alpha3
com/android/support/constraint/constraint-layout/1.0.0-alpha2
com/android/support/constraint/constraint-layout-solver/1.0.0-alpha8
com/android/support/constraint/constraint-layout-solver/1.0.0-alpha7
com/android/support/constraint/constraint-layout-solver/1.0.0-alpha6
com/android/support/constraint/constraint-layout-solver/1.0.0-alpha5
com/android/support/constraint/constraint-layout-solver/1.0.0-alpha4
com/android/support/constraint/constraint-layout-solver/1.0.0-alpha3
com/android/support/constraint/constraint-layout-solver/1.0.0-alpha2
com/android/support/constraint/constraint-layout-solver
com/android/support/constraint/constraint-layout
|===

== Android NDK

"android-ndk-r10e" is pre-installed on the box.
