--- 
titletext: How to Manually Install the buddybuild Android SDK
description: >
  We highly recommend using the automatic buddybuild Android SDK integration
  from the buddybuild. However, you can install the buddybuild Android SDK
  manually
---
= SDK Manual Integration

We **highly recommend** using the automatic buddybuild SDK integration
right from the buddybuild dashboard.

However, if you wish to install the buddybuild SDK manually, follow the
steps on this page.

**As of July 2016, the method count of the SDK is 1,175.**

== Step 1: Add plugins to build.gradle

In order to pull in the plugins needed to build the app with the SDK,
add the following line to your `build.gradle` file:

[[code-samples]]
--
[source,json]
----
repositories {
    jcenter()

    maven {
        url 'https://dl.bintray.com/buddybuild/maven'
    }
}

dependencies {
    compile 'com.buddybuild:sdk:0.0.84@aar'
    compile 'com.squareup:seismic:1.0.2'
    compile 'com.faendir:acra:4.10.0'
}
----
--

[WARNING]
=========
**Tips**

Two things to note here:

. You can put the "repositories" section in the base build.gradle file,
  but you need to put it under the "allprojects" section.

. Note the "aar" at the end of "com.buddybuild:sdk:0.0.59"
=========

== Step 2: Add Permissions to AndroidManifest.xml

The following permissions allow the SDK to send feedback, as well as to
collect adb log in case of app crash:

[[code-samples]]
--
[source,xml]
----
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.READ_LOGS"/>
----
--

== Step 3: setup SDK on Application.onCreate()

One last thing to do is to start up the SDK upon app start. All you need
to do is to add **BuddyBuild.setup(this)** to your **Application**
class.

[WARNING]
=========
This will **not** work properly when added to the **main activity**
class instead.
=========

[[code-samples]]
--
[source,java]
----
package buddybuild.com.helloworldandroid;

import android.app.Application;
import com.buddybuild.sdk.BuddyBuild;

public class MainApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();

        BuddyBuild.setup(this);
    }
}
----
--
