---
titletext: How to integrate buddybuild's SDK into your apps
description: >
  Integrate the buddybuild SDK to access graphical user feedback
  reports, crash reports, tester usage and analytics, and automatic app
  updates.
---
= Integrate the buddybuild SDK

The buddybuild SDK is a lightweight yet powerful suite of tools that
integrates seamlessly into your application. The SDK includes a
graphical feedback reporter, a crash reporting and analysis tool,
automatic app updating and usage tracking. The SDK is regularly updated
with new features.

The buddybuild SDK is available for both link:ios.adoc[iOS] and
link:android.adoc[Android] platforms and enables the following features:


== Feedback Reporter

With buddybuild, you simply take a screenshot to share feedback. Our
feedback reporter sends graphically annotated screenshots, feedback
notes and device metadata to your team. Integrate with GitHub, JIRA and
Pivotal Tracker to track feedback as issues.
link:../../sdk/feedback_reporter.adoc[Learn more.]

== Instant Replay

No more emailing testers for repro steps. Along with each crash report,
buddybuild will also attach a 15 second video of your testers'
interactions with your App's UI right up to the point where it crashed
-- allowing you to instantly see what they did to cause a crash.

== Automatic Update

Receiving feedback on old builds is pointless -- you've probably already
fixed the issue you've received feedback on! It is crucial to keep your
testers and beta users updated on the very latest builds. If a newer
build is available, the buddybuild SDK can automatically prompt to
install the latest version of your app.
link:../../sdk/automatic_update.adoc[Learn more.]

== Usage Tracking

Know when your testers download and launch your app in real time.
Identify who tested your app, when they launched it and what version
they tested. Correlate this with feedback and crash reports to
understand your customers' experience.
link:../../sdk/usage_tracking.adoc[Learn more.]
