= Builds FAQ

This section provides answers to frequently-asked build questions. See
the link:../troubleshooting/README.adoc[Troubleshooting] section for
solutions to a variety of build problems.

== How do I build a specific commit?

- Create a branch pointing to the specific commit. Then use the
  link:https://apidocs.buddybuild.com/builds/post-trigger.html[REST API]
  to trigger a build for that branch.

- Push a tag that includes the desired commit.

- Click the **Rebuild** button for a previous build of the commit.


== How do I delete the history of builds from an old branch?

While buddybuild tracks the history and feedback for all builds, you can
make builds for old branches less visible:

- Delete the branch if you no longer need it. When you have deleted
  branches, a **deleted branches** link appears at the bottom of the
  **Builds** page in the Dashboard; click that link to view the builds
  for deleted branches.

- Create additional branches; new branches push old branches out of
  view on the **Builds** page.
