---
titletext: How to connect your mobile app repositories to buddybuild
description: >
  Buddybuild supports Bitbucket, Bitbucket Server, GitHub, GitHub
  Enterprise, GitLab, a privately-hosted GitLab instance, and SSH (most
  other repositories).
---
= Quickstart

This section describes how to quickly get started using buddybuild.
Overall, the process involves a few steps:


. **Connect buddybuild to your project's source control**
+
Buddybuild supports the follow source control providers:
+
- link:connect/bitbucket.adoc[Bitbucket]
- link:connect/bitbucket_server.adoc[Bitbucket Server]
- link:connect/github.adoc[GitHub]
- link:connect/github_enterprise.adoc[GitHub Enterprise]
- link:connect/gitlab.adoc[GitLab]
- link:connect/gitlab_private.adoc[a privately-hosted GitLab instance]
- link:connect/ssh.adoc[SSH (most other repositories)]

. link:select.adoc[**Choose a repository**]
+
Buddybuild examines your repository and automatically configures builds
based on the configuration that you have setup.
+
[NOTE]
======
If you have multiple build targets defined for your iOS app, you need to
complete the Quickstart process once for each target.
======

. link:invite_testers.adoc[**Invite testers**]
+
This step prepares your app for deployment to your testers. For iOS
projects, this involves uploading code signing identities.

Optional additional steps include:

. link:integrate_sdk.adoc[**Integrate the buddybuild SDK**]
+
The buddybuild SDK adds useful features that makes it easy to
gather feedback from your testers, and to collect crash reports.

. link:auto_versioning.adoc[**Auto-versioning**]
+
Buddybuild can automatically update the build version, which helps
inform your testers when a new version is available.

. link:tests.adoc[**Tests**]
+
Buddybuild can automatically detect any unit tests included in your
project; we have a list of link:../tests/frameworks.adoc[supported
frameworks], and link:../tests/custom.adoc[instructions] for integrating
unsupported test frameworks. Unit tests are disabled by default, to
ensure that your builds complete as quickly as possible, but you can
enable them at any time.


== Additional topics

- link:apple_developer_portal.adoc[Connect to the Apple Developer
  Portal]
- link:upload_certificates.adoc[Upload your iOS certificates]
