---
description: >
  This section covers the three sets of variables that buddybuild let you define
  to securely propagate your credentials to your build and app.
---
= Build secrets

You might have API keys, access tokens, or other secrets that your app
needs to consume -- either at run time or during a build. However, you
might not want to check these secrets into your source code to make them
available to your app.

In order to securely propagate your credentials to your build and app,
buddybuild provides three sets of variables that you can define:

. link:environment_variables.adoc[Environment Variables] (made available
  to your build time scripts)

. link:device_variables.adoc[Device Variables] (available to your app
  at run time via the buddybuild SDK)

. link:secure_files.adoc[Secure Files] (files made available to your
  build time scripts)

If your app involves cross-repository pull requests, which are pull
requests against a fork of your repository, buddybuild does
not expose any secure environment variables, device variables, or secure
files during cross-repository builds. By default, such secrets are only
available to pull requests coming from the same organization and
repository.

As such a restriction may impact your app's development workflow,
buddybuild's dashboard allows you to specify which forked repositories
to build when pull requests are created. See
link:../pull_requests.adoc#cross-repo[Cross-repository pull requests]
for details.

{% include "/_common/warning-cross_repo_builds.adoc" %}
