---
titletext: Auto-update users with in-app prompts for new builds
description: >
  The buddybuild SDK's automatic update feature notifies testers with an in-app
  prompt whenever a new build is available.
---
= Automatic Update

Receiving feedback on old builds is pointless -- you've probably already
fixed the issue you've received feedback on! It is crucial to keep your
testers and beta users updated on the very latest builds.

Using the buddybuild SDK, testers will receive an in-app prompt to
install a new build once it’s been deployed.

[NOTE]
======
**There are three ways to set up deployments within buddybuild:**

- link:../deployments/manual.adoc[Deploy Manually]
- link:../deployments/automatic.adoc[Deploy Automatically]
- link:../deployments/scheduled.adoc[Scheduled Deployments]
======

Once deployments have been set up, simply
link:../quickstart/ios/integrate_sdk.adoc[integrate the the buddybuild
SDK] into your app to enable the **Automatic Update** feature.

The SDK also offers several other features in addition to Automatic
Updates. Follow the links below to learn more about you can supercharge
your app with the buddybuild SDK.

- link:feedback_reporter.adoc[Feedback Reporter]
- link:usage_tracking.adoc[Usage Tracking]
