---
titletext: Native support for Cordova / Ionic apps
description: >
  Buddybuild supports Cordova / Ionic apps.
---
= Cordova / Ionic Setup

Buddybuild natively supports Cordova / Ionic apps.

There are three steps to make sure that your Cordova / Ionic project is
ready to onboard onto buddybuild.

. The `config.xml` file is checked into your repository

. The `package.json` file is checked into your repository

. The `www` directory is checked into your repository

After you've confirmed that both of those conditions have been met,
you're ready to link:{{readme.path}}/quickstart/select.adoc[add them to
buddybuild!]

NOTE: You need to add each platform as a separate app in buddybuild.


== Does your app require custom tasks?

If you have custom tasks (i.e gulp, webpack) that are required to
correctly configure or setup your Cordova / Ionic application, the
recommended solution is to add a **postinstall** step to your
`package.json` file.

.package.json
[source,json]
----
{
  "scripts" : {
    "postinstall" : "gulp sass build --force-build"
  }
}
----

There's also a hook to do any further configuration in the midst of us
running our Cordova workflow. By adding a `buddybuild_midcordova.sh`
script, you can perform arbitrary operations, such as gulp tasks etc.,
before we start adding your platform and generating resources.
